In [1]:
import pandas as pd

results = pd.DataFrame([
    {
        "model": "Logistic Regression",
        "features": "Full",
        "AUROC": 0.8101148,
        "AUPRC": 0.8216660,
        "Brier": 0.1762288,
        "ECE": 0.0352121
    },
    {
        "model": "Logistic Regression",
        "features": "Robust",
        "AUROC": 0.8019971,
        "AUPRC": 0.8130447
    },
    {
        "model": "XGBoost",
        "features": "Full",
        "AUROC": 0.8955333,
        "AUPRC": 0.9036901,
        "Brier": 0.1310519,
        "ECE": 0.0164373
    },
    {
        "model": "XGBoost",
        "features": "Context Ablation",
        "AUROC": 0.8812946,
        "AUPRC": 0.8890450
    }
])

results

,model,features,AUROC,AUPRC,Brier,ECE
0,Logistic Regression,Full,0.810115,0.821666,0.176229,0.035212
1,Logistic Regression,Robust,0.801997,0.813045,NaN,NaN
2,XGBoost,Full,0.895533,0.903690,0.131052,0.016437
3,XGBoost,Context Ablation,0.881295,0.889045,NaN,NaN

In [2]:
results.to_csv(
    "../experiments/model_comparison.csv",
    index=False
)

print("Saved model comparison.")

Saved model comparison.

In [3]:
results.loc[
    results["model"].eq("XGBoost") &
    results["features"].eq("Context Ablation"),
    "Brier"
] = 0.1399986296892166

results.loc[
    results["model"].eq("XGBoost") &
    results["features"].eq("Context Ablation"),
    "ECE"
] = 0.01773121569949766

results

,model,features,AUROC,AUPRC,Brier,ECE
0,Logistic Regression,Full,0.810115,0.821666,0.176229,0.035212
1,Logistic Regression,Robust,0.801997,0.813045,NaN,NaN
2,XGBoost,Full,0.895533,0.903690,0.131052,0.016437
3,XGBoost,Context Ablation,0.881295,0.889045,0.139999,0.017731

In [4]:
results.to_csv(
    "../experiments/model_comparison.csv",
    index=False
)

In [5]:
cross_dataset_results = pd.DataFrame([
    {
        "train_dataset": "halueval",
        "test_dataset": "truthfulqa",
        "AUROC": 0.525130106836627,
        "AUPRC": 0.5797360971802221
    },
    {
        "train_dataset": "halueval",
        "test_dataset": "fever",
        "AUROC": 0.5458200576543771,
        "AUPRC": 0.5108144916397975
    }
])

cross_dataset_results

  train_dataset test_dataset    AUROC     AUPRC
0      halueval   truthfulqa  0.52513  0.579736
1      halueval        fever  0.54582  0.510814

In [6]:
cross_dataset_results.to_csv(
    "../experiments/cross_dataset_results.csv",
    index=False
)